### ISSUE TITLE
Highlighting Issue

### ISSUE THREAD

**Issue by dylankemp** [Tanza3D/kbin-familiarity-theme#1]
![highlightissue](https://github.com/Tanza3D/kbin-familiarity-theme/assets/60017391/53b29395-2965-44b4-a92d-adedc621ed3e)
Small highlighting issue when I scroll over main topic

**Comment by Tanza3D** [comment]
hm, thought i'd fixed this, will look into it in a bit

**Comment by Tanza3D** [comment]
should be good
