### ISSUE TITLE
Thread actions text grouping (minor issue with Kbin Usability Pack)

### ISSUE THREAD

**Issue by yGns** [Tanza3D/kbin-familiarity-theme#2]
Having an issue with the text on the bottom row of the "thread title card" (is this what it's called?)... this one [here](https://imgur.com/a/JYRFsn0) <- this also highlights the issue

The text for [ _ comments/boost/more ] gets really bunched up if the thread has a media preview icon. It is **not** affected by having comment preview button on or off. Issue is resolved by disabling KUP.

I have tried disabling all other userscripts and userstyles except this style and KUP, but it persists.

**Comment by Tanza3D** [comment]
is the screenshot you sent from this theme? if so then something else is definitely affecting it, since it looks nothing like this on my end.
![image](https://github.com/Tanza3D/kbin-familiarity-theme/assets/33783503/1e48e096-5ca5-475d-b733-89c65e989933)

**Comment by Tanza3D** [comment]
to be clear im using KUP as well, maybe you have some special option turned on from it?

**Comment by yGns** [comment]
I updated, then deactivated everything. I'll leave a few screenshots: [scripts off](https://imgur.com/a/AzUlkPQ), [styles off](https://imgur.com/a/PX9cHRT), [settings](https://imgur.com/a/PX9cHRT), [issue](https://imgur.com/a/PX9cHRT) better - only two things are buncehed and offset now.

Also, I haven't mentioned this before: on [latest version of Vivaldi](https://imgur.com/a/vB0MqIn) (chromium based)

**Comment by yGns** [comment]
Ok... please mark this as resolved. It was a usercss thing in-browser. Messed up everything. Sorry for the bother .

**Comment by Tanza3D** [comment]
ahh makes sense no worries
